name: kids_vax_proj_runner

on:
  schedule:
    - cron: '55 2 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scheduled:
    # The type of runner that the job will run on
    runs-on: macOS-latest
    # retrieve secrets from github
    env:
        RENV_PATHS_ROOT: ~/.local/share/renv
    #
    steps:
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: setup-r
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.2'
      # install renv package
      - run: R -e 'install.packages("renv")'
      # set up cache
      - name: Cache packages
        uses: actions/cache@v2
        with:
           path: ${{ env.RENV_PATHS_ROOT }}
           key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
           restore-keys: |-
              ${{ runner.os }}-renv-
      # - run: sudo apt install -y --no-install-recommends libcurl4-openssl-dev
      # install c++ dependencies and install necessary packages
      - run: R -e 'renv::restore()'
      # execute Rscript
      - run: Rscript verywell_health_kids_covid_vax_projection_june_1.R
        env: 
          DW_API_KEY: ${{ secrets.DW_API_KEY }}
          SCT_PW: ${{ secrets.SCT_PW }}
      # push to git repo
      - name: Add and commit
        id: add_commit
        uses: EndBug/add-and-commit@v8
        with:
          committer_name: Automated
          committer_email: actions@users.noreply.github.com
          message: "Latest data"